// This file is generated by rust-protobuf 2.8.0. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `SMM2Course.proto`

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_8_0;

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(Serialize, Deserialize))]
pub struct SMM2Course {
    // message fields
    pub modified: u64,
    pub title: ::std::string::String,
    pub description: ::std::string::String,
    pub game_style: SMM2Course_GameStyle,
    pub course_theme: SMM2Course_CourseTheme,
    pub course_theme_sub: SMM2Course_CourseTheme,
    pub time: u32,
    pub start_y: u32,
    pub finish_y: u32,
    pub finish_x: u32,
    pub water_max: u32,
    pub water_mode: SMM2Course_WaterMode,
    pub water_speed: SMM2Course_WaterSpeed,
    pub water_min: u32,
    pub auto_scroll: SMM2Course_AutoScroll,
    pub auto_scroll_sub: SMM2Course_AutoScroll,
    pub clear_condition_type: SMM2Course_ClearConditionType,
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a SMM2Course {
    fn default() -> &'a SMM2Course {
        <SMM2Course as ::protobuf::Message>::default_instance()
    }
}

impl SMM2Course {
    pub fn new() -> SMM2Course {
        ::std::default::Default::default()
    }

    // uint64 modified = 1;


    pub fn get_modified(&self) -> u64 {
        self.modified
    }
    pub fn clear_modified(&mut self) {
        self.modified = 0;
    }

    // Param is passed by value, moved
    pub fn set_modified(&mut self, v: u64) {
        self.modified = v;
    }

    // string title = 2;


    pub fn get_title(&self) -> &str {
        &self.title
    }
    pub fn clear_title(&mut self) {
        self.title.clear();
    }

    // Param is passed by value, moved
    pub fn set_title(&mut self, v: ::std::string::String) {
        self.title = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_title(&mut self) -> &mut ::std::string::String {
        &mut self.title
    }

    // Take field
    pub fn take_title(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.title, ::std::string::String::new())
    }

    // string description = 3;


    pub fn get_description(&self) -> &str {
        &self.description
    }
    pub fn clear_description(&mut self) {
        self.description.clear();
    }

    // Param is passed by value, moved
    pub fn set_description(&mut self, v: ::std::string::String) {
        self.description = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_description(&mut self) -> &mut ::std::string::String {
        &mut self.description
    }

    // Take field
    pub fn take_description(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.description, ::std::string::String::new())
    }

    // .cemu_smm.SMM2Course.GameStyle game_style = 4;


    pub fn get_game_style(&self) -> SMM2Course_GameStyle {
        self.game_style
    }
    pub fn clear_game_style(&mut self) {
        self.game_style = SMM2Course_GameStyle::M1;
    }

    // Param is passed by value, moved
    pub fn set_game_style(&mut self, v: SMM2Course_GameStyle) {
        self.game_style = v;
    }

    // .cemu_smm.SMM2Course.CourseTheme course_theme = 5;


    pub fn get_course_theme(&self) -> SMM2Course_CourseTheme {
        self.course_theme
    }
    pub fn clear_course_theme(&mut self) {
        self.course_theme = SMM2Course_CourseTheme::GROUND;
    }

    // Param is passed by value, moved
    pub fn set_course_theme(&mut self, v: SMM2Course_CourseTheme) {
        self.course_theme = v;
    }

    // .cemu_smm.SMM2Course.CourseTheme course_theme_sub = 6;


    pub fn get_course_theme_sub(&self) -> SMM2Course_CourseTheme {
        self.course_theme_sub
    }
    pub fn clear_course_theme_sub(&mut self) {
        self.course_theme_sub = SMM2Course_CourseTheme::GROUND;
    }

    // Param is passed by value, moved
    pub fn set_course_theme_sub(&mut self, v: SMM2Course_CourseTheme) {
        self.course_theme_sub = v;
    }

    // uint32 time = 7;


    pub fn get_time(&self) -> u32 {
        self.time
    }
    pub fn clear_time(&mut self) {
        self.time = 0;
    }

    // Param is passed by value, moved
    pub fn set_time(&mut self, v: u32) {
        self.time = v;
    }

    // uint32 start_y = 8;


    pub fn get_start_y(&self) -> u32 {
        self.start_y
    }
    pub fn clear_start_y(&mut self) {
        self.start_y = 0;
    }

    // Param is passed by value, moved
    pub fn set_start_y(&mut self, v: u32) {
        self.start_y = v;
    }

    // uint32 finish_y = 9;


    pub fn get_finish_y(&self) -> u32 {
        self.finish_y
    }
    pub fn clear_finish_y(&mut self) {
        self.finish_y = 0;
    }

    // Param is passed by value, moved
    pub fn set_finish_y(&mut self, v: u32) {
        self.finish_y = v;
    }

    // uint32 finish_x = 10;


    pub fn get_finish_x(&self) -> u32 {
        self.finish_x
    }
    pub fn clear_finish_x(&mut self) {
        self.finish_x = 0;
    }

    // Param is passed by value, moved
    pub fn set_finish_x(&mut self, v: u32) {
        self.finish_x = v;
    }

    // uint32 water_max = 11;


    pub fn get_water_max(&self) -> u32 {
        self.water_max
    }
    pub fn clear_water_max(&mut self) {
        self.water_max = 0;
    }

    // Param is passed by value, moved
    pub fn set_water_max(&mut self, v: u32) {
        self.water_max = v;
    }

    // .cemu_smm.SMM2Course.WaterMode water_mode = 12;


    pub fn get_water_mode(&self) -> SMM2Course_WaterMode {
        self.water_mode
    }
    pub fn clear_water_mode(&mut self) {
        self.water_mode = SMM2Course_WaterMode::FIXED;
    }

    // Param is passed by value, moved
    pub fn set_water_mode(&mut self, v: SMM2Course_WaterMode) {
        self.water_mode = v;
    }

    // .cemu_smm.SMM2Course.WaterSpeed water_speed = 13;


    pub fn get_water_speed(&self) -> SMM2Course_WaterSpeed {
        self.water_speed
    }
    pub fn clear_water_speed(&mut self) {
        self.water_speed = SMM2Course_WaterSpeed::NONE;
    }

    // Param is passed by value, moved
    pub fn set_water_speed(&mut self, v: SMM2Course_WaterSpeed) {
        self.water_speed = v;
    }

    // uint32 water_min = 14;


    pub fn get_water_min(&self) -> u32 {
        self.water_min
    }
    pub fn clear_water_min(&mut self) {
        self.water_min = 0;
    }

    // Param is passed by value, moved
    pub fn set_water_min(&mut self, v: u32) {
        self.water_min = v;
    }

    // .cemu_smm.SMM2Course.AutoScroll auto_scroll = 15;


    pub fn get_auto_scroll(&self) -> SMM2Course_AutoScroll {
        self.auto_scroll
    }
    pub fn clear_auto_scroll(&mut self) {
        self.auto_scroll = SMM2Course_AutoScroll::NONE;
    }

    // Param is passed by value, moved
    pub fn set_auto_scroll(&mut self, v: SMM2Course_AutoScroll) {
        self.auto_scroll = v;
    }

    // .cemu_smm.SMM2Course.AutoScroll auto_scroll_sub = 16;


    pub fn get_auto_scroll_sub(&self) -> SMM2Course_AutoScroll {
        self.auto_scroll_sub
    }
    pub fn clear_auto_scroll_sub(&mut self) {
        self.auto_scroll_sub = SMM2Course_AutoScroll::NONE;
    }

    // Param is passed by value, moved
    pub fn set_auto_scroll_sub(&mut self, v: SMM2Course_AutoScroll) {
        self.auto_scroll_sub = v;
    }

    // .cemu_smm.SMM2Course.ClearConditionType clear_condition_type = 17;


    pub fn get_clear_condition_type(&self) -> SMM2Course_ClearConditionType {
        self.clear_condition_type
    }
    pub fn clear_clear_condition_type(&mut self) {
        self.clear_condition_type = SMM2Course_ClearConditionType::NONE;
    }

    // Param is passed by value, moved
    pub fn set_clear_condition_type(&mut self, v: SMM2Course_ClearConditionType) {
        self.clear_condition_type = v;
    }
}

impl ::protobuf::Message for SMM2Course {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.modified = tmp;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.title)?;
                },
                3 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.description)?;
                },
                4 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.game_style, 4, &mut self.unknown_fields)?
                },
                5 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.course_theme, 5, &mut self.unknown_fields)?
                },
                6 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.course_theme_sub, 6, &mut self.unknown_fields)?
                },
                7 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.time = tmp;
                },
                8 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.start_y = tmp;
                },
                9 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.finish_y = tmp;
                },
                10 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.finish_x = tmp;
                },
                11 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.water_max = tmp;
                },
                12 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.water_mode, 12, &mut self.unknown_fields)?
                },
                13 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.water_speed, 13, &mut self.unknown_fields)?
                },
                14 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.water_min = tmp;
                },
                15 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.auto_scroll, 15, &mut self.unknown_fields)?
                },
                16 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.auto_scroll_sub, 16, &mut self.unknown_fields)?
                },
                17 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.clear_condition_type, 17, &mut self.unknown_fields)?
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.modified != 0 {
            my_size += ::protobuf::rt::value_size(1, self.modified, ::protobuf::wire_format::WireTypeVarint);
        }
        if !self.title.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.title);
        }
        if !self.description.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.description);
        }
        if self.game_style != SMM2Course_GameStyle::M1 {
            my_size += ::protobuf::rt::enum_size(4, self.game_style);
        }
        if self.course_theme != SMM2Course_CourseTheme::GROUND {
            my_size += ::protobuf::rt::enum_size(5, self.course_theme);
        }
        if self.course_theme_sub != SMM2Course_CourseTheme::GROUND {
            my_size += ::protobuf::rt::enum_size(6, self.course_theme_sub);
        }
        if self.time != 0 {
            my_size += ::protobuf::rt::value_size(7, self.time, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.start_y != 0 {
            my_size += ::protobuf::rt::value_size(8, self.start_y, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.finish_y != 0 {
            my_size += ::protobuf::rt::value_size(9, self.finish_y, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.finish_x != 0 {
            my_size += ::protobuf::rt::value_size(10, self.finish_x, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.water_max != 0 {
            my_size += ::protobuf::rt::value_size(11, self.water_max, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.water_mode != SMM2Course_WaterMode::FIXED {
            my_size += ::protobuf::rt::enum_size(12, self.water_mode);
        }
        if self.water_speed != SMM2Course_WaterSpeed::NONE {
            my_size += ::protobuf::rt::enum_size(13, self.water_speed);
        }
        if self.water_min != 0 {
            my_size += ::protobuf::rt::value_size(14, self.water_min, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.auto_scroll != SMM2Course_AutoScroll::NONE {
            my_size += ::protobuf::rt::enum_size(15, self.auto_scroll);
        }
        if self.auto_scroll_sub != SMM2Course_AutoScroll::NONE {
            my_size += ::protobuf::rt::enum_size(16, self.auto_scroll_sub);
        }
        if self.clear_condition_type != SMM2Course_ClearConditionType::NONE {
            my_size += ::protobuf::rt::enum_size(17, self.clear_condition_type);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if self.modified != 0 {
            os.write_uint64(1, self.modified)?;
        }
        if !self.title.is_empty() {
            os.write_string(2, &self.title)?;
        }
        if !self.description.is_empty() {
            os.write_string(3, &self.description)?;
        }
        if self.game_style != SMM2Course_GameStyle::M1 {
            os.write_enum(4, self.game_style.value())?;
        }
        if self.course_theme != SMM2Course_CourseTheme::GROUND {
            os.write_enum(5, self.course_theme.value())?;
        }
        if self.course_theme_sub != SMM2Course_CourseTheme::GROUND {
            os.write_enum(6, self.course_theme_sub.value())?;
        }
        if self.time != 0 {
            os.write_uint32(7, self.time)?;
        }
        if self.start_y != 0 {
            os.write_uint32(8, self.start_y)?;
        }
        if self.finish_y != 0 {
            os.write_uint32(9, self.finish_y)?;
        }
        if self.finish_x != 0 {
            os.write_uint32(10, self.finish_x)?;
        }
        if self.water_max != 0 {
            os.write_uint32(11, self.water_max)?;
        }
        if self.water_mode != SMM2Course_WaterMode::FIXED {
            os.write_enum(12, self.water_mode.value())?;
        }
        if self.water_speed != SMM2Course_WaterSpeed::NONE {
            os.write_enum(13, self.water_speed.value())?;
        }
        if self.water_min != 0 {
            os.write_uint32(14, self.water_min)?;
        }
        if self.auto_scroll != SMM2Course_AutoScroll::NONE {
            os.write_enum(15, self.auto_scroll.value())?;
        }
        if self.auto_scroll_sub != SMM2Course_AutoScroll::NONE {
            os.write_enum(16, self.auto_scroll_sub.value())?;
        }
        if self.clear_condition_type != SMM2Course_ClearConditionType::NONE {
            os.write_enum(17, self.clear_condition_type.value())?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> SMM2Course {
        SMM2Course::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "modified",
                    |m: &SMM2Course| { &m.modified },
                    |m: &mut SMM2Course| { &mut m.modified },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "title",
                    |m: &SMM2Course| { &m.title },
                    |m: &mut SMM2Course| { &mut m.title },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "description",
                    |m: &SMM2Course| { &m.description },
                    |m: &mut SMM2Course| { &mut m.description },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<SMM2Course_GameStyle>>(
                    "game_style",
                    |m: &SMM2Course| { &m.game_style },
                    |m: &mut SMM2Course| { &mut m.game_style },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<SMM2Course_CourseTheme>>(
                    "course_theme",
                    |m: &SMM2Course| { &m.course_theme },
                    |m: &mut SMM2Course| { &mut m.course_theme },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<SMM2Course_CourseTheme>>(
                    "course_theme_sub",
                    |m: &SMM2Course| { &m.course_theme_sub },
                    |m: &mut SMM2Course| { &mut m.course_theme_sub },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                    "time",
                    |m: &SMM2Course| { &m.time },
                    |m: &mut SMM2Course| { &mut m.time },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                    "start_y",
                    |m: &SMM2Course| { &m.start_y },
                    |m: &mut SMM2Course| { &mut m.start_y },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                    "finish_y",
                    |m: &SMM2Course| { &m.finish_y },
                    |m: &mut SMM2Course| { &mut m.finish_y },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                    "finish_x",
                    |m: &SMM2Course| { &m.finish_x },
                    |m: &mut SMM2Course| { &mut m.finish_x },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                    "water_max",
                    |m: &SMM2Course| { &m.water_max },
                    |m: &mut SMM2Course| { &mut m.water_max },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<SMM2Course_WaterMode>>(
                    "water_mode",
                    |m: &SMM2Course| { &m.water_mode },
                    |m: &mut SMM2Course| { &mut m.water_mode },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<SMM2Course_WaterSpeed>>(
                    "water_speed",
                    |m: &SMM2Course| { &m.water_speed },
                    |m: &mut SMM2Course| { &mut m.water_speed },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                    "water_min",
                    |m: &SMM2Course| { &m.water_min },
                    |m: &mut SMM2Course| { &mut m.water_min },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<SMM2Course_AutoScroll>>(
                    "auto_scroll",
                    |m: &SMM2Course| { &m.auto_scroll },
                    |m: &mut SMM2Course| { &mut m.auto_scroll },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<SMM2Course_AutoScroll>>(
                    "auto_scroll_sub",
                    |m: &SMM2Course| { &m.auto_scroll_sub },
                    |m: &mut SMM2Course| { &mut m.auto_scroll_sub },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<SMM2Course_ClearConditionType>>(
                    "clear_condition_type",
                    |m: &SMM2Course| { &m.clear_condition_type },
                    |m: &mut SMM2Course| { &mut m.clear_condition_type },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<SMM2Course>(
                    "SMM2Course",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static SMM2Course {
        static mut instance: ::protobuf::lazy::Lazy<SMM2Course> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const SMM2Course,
        };
        unsafe {
            instance.get(SMM2Course::new)
        }
    }
}

impl ::protobuf::Clear for SMM2Course {
    fn clear(&mut self) {
        self.modified = 0;
        self.title.clear();
        self.description.clear();
        self.game_style = SMM2Course_GameStyle::M1;
        self.course_theme = SMM2Course_CourseTheme::GROUND;
        self.course_theme_sub = SMM2Course_CourseTheme::GROUND;
        self.time = 0;
        self.start_y = 0;
        self.finish_y = 0;
        self.finish_x = 0;
        self.water_max = 0;
        self.water_mode = SMM2Course_WaterMode::FIXED;
        self.water_speed = SMM2Course_WaterSpeed::NONE;
        self.water_min = 0;
        self.auto_scroll = SMM2Course_AutoScroll::NONE;
        self.auto_scroll_sub = SMM2Course_AutoScroll::NONE;
        self.clear_condition_type = SMM2Course_ClearConditionType::NONE;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for SMM2Course {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SMM2Course {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(Clone,PartialEq,Eq,Debug,Hash)]
#[cfg_attr(feature = "with-serde", derive(Serialize, Deserialize))]
pub enum SMM2Course_GameStyle {
    M1 = 0,
    M3 = 1,
    MW = 2,
    WU = 3,
    W3 = 4,
}

impl ::protobuf::ProtobufEnum for SMM2Course_GameStyle {
    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<SMM2Course_GameStyle> {
        match value {
            0 => ::std::option::Option::Some(SMM2Course_GameStyle::M1),
            1 => ::std::option::Option::Some(SMM2Course_GameStyle::M3),
            2 => ::std::option::Option::Some(SMM2Course_GameStyle::MW),
            3 => ::std::option::Option::Some(SMM2Course_GameStyle::WU),
            4 => ::std::option::Option::Some(SMM2Course_GameStyle::W3),
            _ => ::std::option::Option::None
        }
    }

    fn values() -> &'static [Self] {
        static values: &'static [SMM2Course_GameStyle] = &[
            SMM2Course_GameStyle::M1,
            SMM2Course_GameStyle::M3,
            SMM2Course_GameStyle::MW,
            SMM2Course_GameStyle::WU,
            SMM2Course_GameStyle::W3,
        ];
        values
    }

    fn enum_descriptor_static() -> &'static ::protobuf::reflect::EnumDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::EnumDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                ::protobuf::reflect::EnumDescriptor::new("SMM2Course_GameStyle", file_descriptor_proto())
            })
        }
    }
}

impl ::std::marker::Copy for SMM2Course_GameStyle {
}

impl ::std::default::Default for SMM2Course_GameStyle {
    fn default() -> Self {
        SMM2Course_GameStyle::M1
    }
}

impl ::protobuf::reflect::ProtobufValue for SMM2Course_GameStyle {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Enum(self.descriptor())
    }
}

#[derive(Clone,PartialEq,Eq,Debug,Hash)]
#[cfg_attr(feature = "with-serde", derive(Serialize, Deserialize))]
pub enum SMM2Course_CourseTheme {
    GROUND = 0,
    UNDERGROUND = 1,
    CASTLE = 2,
    AIRSHIP = 3,
    UNDERWATER = 4,
    GHOUST_HOUSE = 5,
    SNOW = 6,
    DESERT = 7,
    SKY = 8,
    FOREST = 9,
}

impl ::protobuf::ProtobufEnum for SMM2Course_CourseTheme {
    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<SMM2Course_CourseTheme> {
        match value {
            0 => ::std::option::Option::Some(SMM2Course_CourseTheme::GROUND),
            1 => ::std::option::Option::Some(SMM2Course_CourseTheme::UNDERGROUND),
            2 => ::std::option::Option::Some(SMM2Course_CourseTheme::CASTLE),
            3 => ::std::option::Option::Some(SMM2Course_CourseTheme::AIRSHIP),
            4 => ::std::option::Option::Some(SMM2Course_CourseTheme::UNDERWATER),
            5 => ::std::option::Option::Some(SMM2Course_CourseTheme::GHOUST_HOUSE),
            6 => ::std::option::Option::Some(SMM2Course_CourseTheme::SNOW),
            7 => ::std::option::Option::Some(SMM2Course_CourseTheme::DESERT),
            8 => ::std::option::Option::Some(SMM2Course_CourseTheme::SKY),
            9 => ::std::option::Option::Some(SMM2Course_CourseTheme::FOREST),
            _ => ::std::option::Option::None
        }
    }

    fn values() -> &'static [Self] {
        static values: &'static [SMM2Course_CourseTheme] = &[
            SMM2Course_CourseTheme::GROUND,
            SMM2Course_CourseTheme::UNDERGROUND,
            SMM2Course_CourseTheme::CASTLE,
            SMM2Course_CourseTheme::AIRSHIP,
            SMM2Course_CourseTheme::UNDERWATER,
            SMM2Course_CourseTheme::GHOUST_HOUSE,
            SMM2Course_CourseTheme::SNOW,
            SMM2Course_CourseTheme::DESERT,
            SMM2Course_CourseTheme::SKY,
            SMM2Course_CourseTheme::FOREST,
        ];
        values
    }

    fn enum_descriptor_static() -> &'static ::protobuf::reflect::EnumDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::EnumDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                ::protobuf::reflect::EnumDescriptor::new("SMM2Course_CourseTheme", file_descriptor_proto())
            })
        }
    }
}

impl ::std::marker::Copy for SMM2Course_CourseTheme {
}

impl ::std::default::Default for SMM2Course_CourseTheme {
    fn default() -> Self {
        SMM2Course_CourseTheme::GROUND
    }
}

impl ::protobuf::reflect::ProtobufValue for SMM2Course_CourseTheme {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Enum(self.descriptor())
    }
}

#[derive(Clone,PartialEq,Eq,Debug,Hash)]
#[cfg_attr(feature = "with-serde", derive(Serialize, Deserialize))]
pub enum SMM2Course_WaterMode {
    FIXED = 0,
    ONE_WAY = 1,
    OSCILLATING = 2,
}

impl ::protobuf::ProtobufEnum for SMM2Course_WaterMode {
    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<SMM2Course_WaterMode> {
        match value {
            0 => ::std::option::Option::Some(SMM2Course_WaterMode::FIXED),
            1 => ::std::option::Option::Some(SMM2Course_WaterMode::ONE_WAY),
            2 => ::std::option::Option::Some(SMM2Course_WaterMode::OSCILLATING),
            _ => ::std::option::Option::None
        }
    }

    fn values() -> &'static [Self] {
        static values: &'static [SMM2Course_WaterMode] = &[
            SMM2Course_WaterMode::FIXED,
            SMM2Course_WaterMode::ONE_WAY,
            SMM2Course_WaterMode::OSCILLATING,
        ];
        values
    }

    fn enum_descriptor_static() -> &'static ::protobuf::reflect::EnumDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::EnumDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                ::protobuf::reflect::EnumDescriptor::new("SMM2Course_WaterMode", file_descriptor_proto())
            })
        }
    }
}

impl ::std::marker::Copy for SMM2Course_WaterMode {
}

impl ::std::default::Default for SMM2Course_WaterMode {
    fn default() -> Self {
        SMM2Course_WaterMode::FIXED
    }
}

impl ::protobuf::reflect::ProtobufValue for SMM2Course_WaterMode {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Enum(self.descriptor())
    }
}

#[derive(Clone,PartialEq,Eq,Debug,Hash)]
#[cfg_attr(feature = "with-serde", derive(Serialize, Deserialize))]
pub enum SMM2Course_WaterSpeed {
    NONE = 0,
    SLOW = 1,
    MEDIUM = 2,
    FAST = 3,
}

impl ::protobuf::ProtobufEnum for SMM2Course_WaterSpeed {
    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<SMM2Course_WaterSpeed> {
        match value {
            0 => ::std::option::Option::Some(SMM2Course_WaterSpeed::NONE),
            1 => ::std::option::Option::Some(SMM2Course_WaterSpeed::SLOW),
            2 => ::std::option::Option::Some(SMM2Course_WaterSpeed::MEDIUM),
            3 => ::std::option::Option::Some(SMM2Course_WaterSpeed::FAST),
            _ => ::std::option::Option::None
        }
    }

    fn values() -> &'static [Self] {
        static values: &'static [SMM2Course_WaterSpeed] = &[
            SMM2Course_WaterSpeed::NONE,
            SMM2Course_WaterSpeed::SLOW,
            SMM2Course_WaterSpeed::MEDIUM,
            SMM2Course_WaterSpeed::FAST,
        ];
        values
    }

    fn enum_descriptor_static() -> &'static ::protobuf::reflect::EnumDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::EnumDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                ::protobuf::reflect::EnumDescriptor::new("SMM2Course_WaterSpeed", file_descriptor_proto())
            })
        }
    }
}

impl ::std::marker::Copy for SMM2Course_WaterSpeed {
}

impl ::std::default::Default for SMM2Course_WaterSpeed {
    fn default() -> Self {
        SMM2Course_WaterSpeed::NONE
    }
}

impl ::protobuf::reflect::ProtobufValue for SMM2Course_WaterSpeed {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Enum(self.descriptor())
    }
}

#[derive(Clone,PartialEq,Eq,Debug,Hash)]
#[cfg_attr(feature = "with-serde", derive(Serialize, Deserialize))]
pub enum SMM2Course_AutoScroll {
    NONE = 0,
    SLOW = 1,
    MEDIUM = 2,
    FAST = 3,
    CUSTOM = 4,
}

impl ::protobuf::ProtobufEnum for SMM2Course_AutoScroll {
    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<SMM2Course_AutoScroll> {
        match value {
            0 => ::std::option::Option::Some(SMM2Course_AutoScroll::NONE),
            1 => ::std::option::Option::Some(SMM2Course_AutoScroll::SLOW),
            2 => ::std::option::Option::Some(SMM2Course_AutoScroll::MEDIUM),
            3 => ::std::option::Option::Some(SMM2Course_AutoScroll::FAST),
            4 => ::std::option::Option::Some(SMM2Course_AutoScroll::CUSTOM),
            _ => ::std::option::Option::None
        }
    }

    fn values() -> &'static [Self] {
        static values: &'static [SMM2Course_AutoScroll] = &[
            SMM2Course_AutoScroll::NONE,
            SMM2Course_AutoScroll::SLOW,
            SMM2Course_AutoScroll::MEDIUM,
            SMM2Course_AutoScroll::FAST,
            SMM2Course_AutoScroll::CUSTOM,
        ];
        values
    }

    fn enum_descriptor_static() -> &'static ::protobuf::reflect::EnumDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::EnumDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                ::protobuf::reflect::EnumDescriptor::new("SMM2Course_AutoScroll", file_descriptor_proto())
            })
        }
    }
}

impl ::std::marker::Copy for SMM2Course_AutoScroll {
}

impl ::std::default::Default for SMM2Course_AutoScroll {
    fn default() -> Self {
        SMM2Course_AutoScroll::NONE
    }
}

impl ::protobuf::reflect::ProtobufValue for SMM2Course_AutoScroll {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Enum(self.descriptor())
    }
}

#[derive(Clone,PartialEq,Eq,Debug,Hash)]
#[cfg_attr(feature = "with-serde", derive(Serialize, Deserialize))]
pub enum SMM2Course_ClearConditionType {
    NONE = 0,
    PARTS = 1,
    STATUS = 2,
    ACTION = 3,
}

impl ::protobuf::ProtobufEnum for SMM2Course_ClearConditionType {
    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<SMM2Course_ClearConditionType> {
        match value {
            0 => ::std::option::Option::Some(SMM2Course_ClearConditionType::NONE),
            1 => ::std::option::Option::Some(SMM2Course_ClearConditionType::PARTS),
            2 => ::std::option::Option::Some(SMM2Course_ClearConditionType::STATUS),
            3 => ::std::option::Option::Some(SMM2Course_ClearConditionType::ACTION),
            _ => ::std::option::Option::None
        }
    }

    fn values() -> &'static [Self] {
        static values: &'static [SMM2Course_ClearConditionType] = &[
            SMM2Course_ClearConditionType::NONE,
            SMM2Course_ClearConditionType::PARTS,
            SMM2Course_ClearConditionType::STATUS,
            SMM2Course_ClearConditionType::ACTION,
        ];
        values
    }

    fn enum_descriptor_static() -> &'static ::protobuf::reflect::EnumDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::EnumDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                ::protobuf::reflect::EnumDescriptor::new("SMM2Course_ClearConditionType", file_descriptor_proto())
            })
        }
    }
}

impl ::std::marker::Copy for SMM2Course_ClearConditionType {
}

impl ::std::default::Default for SMM2Course_ClearConditionType {
    fn default() -> Self {
        SMM2Course_ClearConditionType::NONE
    }
}

impl ::protobuf::reflect::ProtobufValue for SMM2Course_ClearConditionType {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Enum(self.descriptor())
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x10SMM2Course.proto\x12\x08cemu_smm\"\xe1\x08\n\nSMM2Course\x12\x12\n\
    \x08modified\x18\x01\x20\x01(\x04B\0\x12\x0f\n\x05title\x18\x02\x20\x01(\
    \tB\0\x12\x15\n\x0bdescription\x18\x03\x20\x01(\tB\0\x124\n\ngame_style\
    \x18\x04\x20\x01(\x0e2\x1e.cemu_smm.SMM2Course.GameStyleB\0\x128\n\x0cco\
    urse_theme\x18\x05\x20\x01(\x0e2\x20.cemu_smm.SMM2Course.CourseThemeB\0\
    \x12<\n\x10course_theme_sub\x18\x06\x20\x01(\x0e2\x20.cemu_smm.SMM2Cours\
    e.CourseThemeB\0\x12\x0e\n\x04time\x18\x07\x20\x01(\rB\0\x12\x11\n\x07st\
    art_y\x18\x08\x20\x01(\rB\0\x12\x12\n\x08finish_y\x18\t\x20\x01(\rB\0\
    \x12\x12\n\x08finish_x\x18\n\x20\x01(\rB\0\x12\x13\n\twater_max\x18\x0b\
    \x20\x01(\rB\0\x124\n\nwater_mode\x18\x0c\x20\x01(\x0e2\x1e.cemu_smm.SMM\
    2Course.WaterModeB\0\x126\n\x0bwater_speed\x18\r\x20\x01(\x0e2\x1f.cemu_\
    smm.SMM2Course.WaterSpeedB\0\x12\x13\n\twater_min\x18\x0e\x20\x01(\rB\0\
    \x126\n\x0bauto_scroll\x18\x0f\x20\x01(\x0e2\x1f.cemu_smm.SMM2Course.Aut\
    oScrollB\0\x12:\n\x0fauto_scroll_sub\x18\x10\x20\x01(\x0e2\x1f.cemu_smm.\
    SMM2Course.AutoScrollB\0\x12G\n\x14clear_condition_type\x18\x11\x20\x01(\
    \x0e2'.cemu_smm.SMM2Course.ClearConditionTypeB\0\"5\n\tGameStyle\x12\x06\
    \n\x02M1\x10\0\x12\x06\n\x02M3\x10\x01\x12\x06\n\x02MW\x10\x02\x12\x06\n\
    \x02WU\x10\x03\x12\x06\n\x02W3\x10\x04\x1a\0\"\x92\x01\n\x0bCourseTheme\
    \x12\n\n\x06GROUND\x10\0\x12\x0f\n\x0bUNDERGROUND\x10\x01\x12\n\n\x06CAS\
    TLE\x10\x02\x12\x0b\n\x07AIRSHIP\x10\x03\x12\x0e\n\nUNDERWATER\x10\x04\
    \x12\x10\n\x0cGHOUST_HOUSE\x10\x05\x12\x08\n\x04SNOW\x10\x06\x12\n\n\x06\
    DESERT\x10\x07\x12\x07\n\x03SKY\x10\x08\x12\n\n\x06FOREST\x10\t\x1a\0\"6\
    \n\tWaterMode\x12\t\n\x05FIXED\x10\0\x12\x0b\n\x07ONE_WAY\x10\x01\x12\
    \x0f\n\x0bOSCILLATING\x10\x02\x1a\0\"8\n\nWaterSpeed\x12\x08\n\x04NONE\
    \x10\0\x12\x08\n\x04SLOW\x10\x01\x12\n\n\x06MEDIUM\x10\x02\x12\x08\n\x04\
    FAST\x10\x03\x1a\0\"D\n\nAutoScroll\x12\x08\n\x04NONE\x10\0\x12\x08\n\
    \x04SLOW\x10\x01\x12\n\n\x06MEDIUM\x10\x02\x12\x08\n\x04FAST\x10\x03\x12\
    \n\n\x06CUSTOM\x10\x04\x1a\0\"C\n\x12ClearConditionType\x12\x08\n\x04NON\
    E\x10\0\x12\t\n\x05PARTS\x10\x01\x12\n\n\x06STATUS\x10\x02\x12\n\n\x06AC\
    TION\x10\x03\x1a\0:\0B\0b\x06proto3\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy {
    lock: ::protobuf::lazy::ONCE_INIT,
    ptr: 0 as *const ::protobuf::descriptor::FileDescriptorProto,
};

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
